# Generated by Django 3.1.7 on 2021-04-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210402_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, verbose_name='团体名称')),
                ('group_script', models.CharField(max_length=60, verbose_name='备注')),
            ],
        ),
        migrations.RenameField(
            model_name='department',
            old_name='group_script',
            new_name='dep_script',
        ),
        migrations.RemoveField(
            model_name='department',
            name='group_name',
        ),
        migrations.AddField(
            model_name='department',
            name='dep_name',
            field=models.CharField(default='test', max_length=32, verbose_name='部门名称'),
            preserve_default=False,
        ),
    ]
