# Generated by Django 3.2.2 on 2021-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210402_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ManyToManyField(to='myapp.group'),
        ),
    ]
